#!/usr/bin/env bash
# ================================================================
#  Pi 3 COMMAND SERVER — Full Setup Script
#  Run as root: sudo bash setup_pi.sh
# ================================================================
#  This script:
#   1. Configures the Pi as a Wi-Fi hotspot (AP mode)
#   2. Enables IP forwarding + iptables NAT
#   3. Installs & configures Asterisk PBX
#   4. Installs Flask and sets up the web server
#   5. Generates self-signed TLS cert for Asterisk WSS
#   6. Creates systemd services for auto-start
# ================================================================

set -e
PI_IP="10.0.0.1"
AP_SSID="PI_COMMAND_NET"
AP_PASS="rescue2024"
WIFI_IF="wlan0"        # Adjust if needed (ip link show to verify)
ETH_IF="eth0"

echo "================================================================"
echo "  SAR COMMAND SERVER SETUP"
echo "================================================================"

# ── 0. Update system ─────────────────────────────────────────
apt-get update -q
apt-get install -y hostapd dnsmasq iptables-persistent \
                   asterisk python3-flask sqlite3 \
                   openssl net-tools

# ── 1. Configure static IP on wlan0 ─────────────────────────
cat > /etc/dhcpcd.conf << EOF
# Generated by SAR setup script
interface ${WIFI_IF}
    static ip_address=${PI_IP}/24
    nohook wpa_supplicant
EOF

# ── 2. Configure hostapd (Wi-Fi AP) ─────────────────────────
cat > /etc/hostapd/hostapd.conf << EOF
interface=${WIFI_IF}
driver=nl80211
ssid=${AP_SSID}
hw_mode=g
channel=6
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=${AP_PASS}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF

sed -i 's|#DAEMON_CONF=.*|DAEMON_CONF="/etc/hostapd/hostapd.conf"|' \
    /etc/default/hostapd

# ── 3. Configure dnsmasq (DHCP + captive portal DNS) ─────────
# Backup original
[ -f /etc/dnsmasq.conf.orig ] || \
    cp /etc/dnsmasq.conf /etc/dnsmasq.conf.orig

cat > /etc/dnsmasq.conf << EOF
# SAR Command Server — dnsmasq config
interface=${WIFI_IF}
bind-dynamic
dhcp-range=10.0.0.50,10.0.0.150,255.255.255.0,24h
dhcp-option=option:router,${PI_IP}
dhcp-option=option:dns-server,${PI_IP}
server=8.8.8.8
log-queries
log-dhcp

# Captive Portal: resolve ALL DNS to the Pi IP
# This forces the captive portal detection on any device
address=/#/${PI_IP}
EOF

# ── 4. Enable IP forwarding ──────────────────────────────────
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-sar-forward.conf
sysctl -p /etc/sysctl.d/99-sar-forward.conf

# ── 5. iptables rules ────────────────────────────────────────
# NAT outgoing traffic from wlan0 clients through eth0 (if connected)
iptables -t nat -A POSTROUTING -o ${ETH_IF} -j MASQUERADE
iptables -A FORWARD -i ${ETH_IF} -o ${WIFI_IF} -m state \
    --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i ${WIFI_IF} -o ${ETH_IF} -j ACCEPT

# Captive Portal redirect: intercept HTTP to port 80 on the Pi
# This redirects all port 80 traffic (from connected clients) to our Flask server
iptables -t nat -A PREROUTING -i ${WIFI_IF} -p tcp --dport 80 \
    -j DNAT --to-destination ${PI_IP}:80

# Save rules (iptables-persistent)
netfilter-persistent save

# ── 6. Generate self-signed TLS cert for Asterisk WSS ────────
mkdir -p /etc/asterisk/keys
openssl req -x509 -newkey rsa:2048 \
    -keyout /etc/asterisk/keys/ast.key \
    -out    /etc/asterisk/keys/ast.crt \
    -days 3650 -nodes \
    -subj "/C=MA/ST=Rescue/L=SAR/O=UniversityPoC/CN=${PI_IP}"

chown -R asterisk:asterisk /etc/asterisk/keys
chmod 600 /etc/asterisk/keys/ast.key

echo "[CERT] Self-signed cert generated at /etc/asterisk/keys/"

# ── 7. Install Asterisk config files ─────────────────────────
cp /root/sar_setup/asterisk_config/pjsip.conf       /etc/asterisk/pjsip.conf
cp /root/sar_setup/asterisk_config/extensions.conf  /etc/asterisk/extensions.conf

# Generate MD5 for ext 100 password (command100pass)
MD5_100=$(echo -n "100:asterisk:command100pass" | md5sum | awk '{print $1}')
sed -i "s/REPLACE_WITH_MD5_OF_PASS/${MD5_100}/" /etc/asterisk/pjsip.conf

echo "[ASTERISK] Config files installed. MD5 for ext 100: ${MD5_100}"

# ── 8. Setup Flask server ────────────────────────────────────
pip3 install flask --quiet
mkdir -p /opt/sar_server
cp /root/sar_setup/command_server/server.py /opt/sar_server/server.py
mkdir -p /var/db
chmod 777 /var/db  # Allow Flask to write DB

# ── 9. Create systemd services ──────────────────────────────

# Flask service
cat > /etc/systemd/system/sar-server.service << EOF
[Unit]
Description=SAR Command Server (Flask)
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/sar_server
ExecStart=/usr/bin/python3 /opt/sar_server/server.py
Restart=always
RestartSec=5
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable hostapd dnsmasq asterisk sar-server
systemctl start  hostapd dnsmasq asterisk sar-server

echo ""
echo "================================================================"
echo "  SETUP COMPLETE"
echo ""
echo "  Pi 3 AP SSID : ${AP_SSID}  (pass: ${AP_PASS})"
echo "  Pi 3 IP      : ${PI_IP}"
echo "  Web Portal   : http://${PI_IP}/"
echo "  Dashboard    : http://${PI_IP}/dashboard"
echo ""
echo "  Asterisk SIP (UDP) : ${PI_IP}:5060"
echo "  Asterisk WS        : ws://${PI_IP}:8088/ws"
echo "  Asterisk WSS       : wss://${PI_IP}:8089/ws"
echo ""
echo "  Softphone (ext 100): user=100  pass=command100pass"
echo "  WebRTC   (ext 200): user=200  pass=victim200pass"
echo "================================================================"
