[global]
type=global
user_agent=SAR-PBX
default_realm=asterisk
endpoint_identifier_order=username,ip,anonymous

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0:8088

[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0:8089
cert_file=/etc/asterisk/keys/ast.crt
priv_key_file=/etc/asterisk/keys/ast.key

[auth100]
type=auth
auth_type=userpass
username=100
password=command100pass

[100]
type=aor
max_contacts=2

[100]
type=endpoint
context=sar-dialplan
disallow=all
allow=ulaw
allow=alaw
auth=auth100
aors=100
transport=transport-udp
direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes

[auth200]
type=auth
auth_type=userpass
username=200
password=victim200pass

[200]
type=aor
max_contacts=5
remove_existing=yes

[200]
type=endpoint
context=sar-dialplan
disallow=all
allow=ulaw
allow=opus
auth=auth200
aors=200
transport=transport-wss
webrtc=yes
direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes
